MODEL:
  name: 'resnet18'
DATA:
  name: 'cifar-100'
  augmentation: True
  cutout : False
  cutmix : False
  mixup :  False
# cutout config
CUTOUT:
  n_holes: 1
  length: 16
TRAIN:
  device: 'cuda:6'
  batch_size: 128
  epochs: 20
  lr: 0.1